// Pulls the slide fonts out of the published block's html5/data/css/output.min.css
// (Storyline embeds them as base64 @font-face rules) and writes real .woff files plus
// src/fonts.css. The family names are kept EXACTLY as the original uses them, so a
// slide's fontFamily string from the Storyline data can be used as-is in CSS.
// Run:  node tools/extract-fonts.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const css = readFileSync(join(root, 'source/storyline-published/html5/data/css/output.min.css'), 'utf8');
const outDir = join(root, 'assets/fonts/storyline');
mkdirSync(outDir, { recursive: true });

const blocks = [...css.matchAll(/@font-face\s*{([^}]*)}/g)].map(m => m[1]);
const seen = new Map(); // base64 → filename (dedupe identical data)
const rules = [];
for (const b of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(b)?.[1];
  const data = /base64,([A-Za-z0-9+/=]+)/.exec(b)?.[1];
  if (!family || !data) continue;
  const weight = /font-weight:\s*([^;]+);/.exec(b)?.[1].trim() || 'normal';
  const style = /font-style:\s*([^;]+);/.exec(b)?.[1].trim() || 'normal';
  const range = /unicode-range:\s*([^;]+);/.exec(b)?.[1].trim();
  let file = seen.get(data);
  if (!file) {
    const slug = family.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase();
    file = `${slug}${weight !== 'normal' ? '-' + weight : ''}${style !== 'normal' ? '-' + style : ''}.woff`;
    writeFileSync(join(outDir, file), Buffer.from(data, 'base64'));
    seen.set(data, file);
  }
  rules.push(`@font-face{font-family:'${family}';src:url(../assets/fonts/storyline/${file}) format('woff');font-weight:${weight};font-style:${style};${range ? `unicode-range:${range};` : ''}font-display:block}`);
}

const header = `/* Fonts. Generated by tools/extract-fonts.mjs — do not edit the Storyline section by hand.
   1. Lato (player chrome) and Open Sans (cover START button, cover footer): self-hosted,
      latin subsets from Google Fonts (SIL Open Font License).
   2. Storyline section: the exact font subsets the published block embeds in
      html5/data/css/output.min.css (Calibri, Calibri Bold, Open Sans, Arial, Lato), under the
      original family names, so slide text renders with the same glyphs as the original. */
@font-face{font-family:'Lato';src:url(../assets/fonts/lato-400.woff2) format('woff2');font-weight:400;font-style:normal;font-display:swap}
@font-face{font-family:'Lato';src:url(../assets/fonts/lato-700.woff2) format('woff2');font-weight:700;font-style:normal;font-display:swap}
@font-face{font-family:'Open Sans';src:url(../assets/fonts/open-sans-variable.woff2) format('woff2');font-weight:300 800;font-style:normal;font-display:swap}
/* --- Storyline subsets (generated) --- */
`;
writeFileSync(join(root, 'src/fonts.css'), header + rules.join('\n') + '\n');
console.log(`${rules.length} @font-face rules, ${seen.size} font files written to assets/fonts/storyline/`);
for (const [, f] of seen) console.log('  ' + f);
